### PR TITLE
First version with subdevices

### PR DESCRIPTION
**Pull request by freemann**
First version with subdevices
Supported are;
-Wind,
-Rain,
-Indoor,
-Outdoor

screenshot - 14-5-2016 17_54_51

### CODE REVIEW

**Comment by Dijker** [comment]
Hi Freeman, 
I tried to use your fork, but ! get some errors. 
First tried upgrading. Removed, restarted and run your version. 
At adding my NetAtmo after a init I get (after Add DEvice - Select  NetAtmo - Popup for Logon - Closes automatic.)
image

and a true in the node.js window:

D:\Homey\Dev>athom project --run com.netatmo-master
? Select active Homey: (Use arrow keys)
? Select active Homey: BerliozHomey @ 10.1.13.107:80
1/4 - Archiving...
2/4 - Uploading to BerliozHomey @ http://10.1.13.107:80...
3/4 - Running `com.netatmo`, press CTRL+C to abort...
4/4 - Debugging...

-------------------------------------------------
init
**true**

Any idea? 
I reverted back to the App strore version

**Comment by freemann** [comment]
@Dijker 
That error brought me a lot of headache for a couple of hours....
Its caused by the missing file "env.json" which contains the NetAtmo API tokens. This file is in the Ignore list, so if you download the source, Git won't serve it to you.

Here's a example of the contents of the file and the tokens are from my Station (I will reset the token within a couple of hours);
```
{
    "CLIENT_ID": "57338562aaa0dddf4da35aef",
    "CLIENT_SECRET": "JaZJmq6pWg7VHpqAfXHAThk9IQMMhlm"
}
```
create the file in the root of the project dir and run the project again on your Homey.

You could create you own "application" on https://dev.netatmo.com/dev/createapp and that gives you your own tokens.

Hopes it help!

**Comment by Dijker** [comment]
Ahhh, I guess that file is normally available in the Athom app store but not in the public repository. 
I will try tomorrow and create my own app for the test. Thanks for your response. Will let you know the results.

**Comment by Dijker** [comment]
Great! 
Thanks it works with your env.json!
I added all NetAtmo Modules, I only had to remove the old device (guess the internal ID changed)

I wanted to request my own App/ Development ID's 
What should I enter at the Redirect URI (Callback URL)? 

It works!, I get only one msg at the node.js prompt. it looks like it repeats after several minutes (approx. 5 ?):
4/4 - Debugging...
-------------------------------------------------
init
{ code: 10, message: 'Argument(s) is(are) missing' }
{ code: 10, message: 'Argument(s) is(are) missing' }

I installed it for testing !!

**Comment by freemann** [comment]
Internal ID's are changed and will have a look if I can make it more backwards compatible.
Will look at the code:10 and the come every 5 min because of a 5 min interval which receives the most up2date station info.

Thanx!

**Comment by BasKiers** [comment]
Hi, I'm currently working on the integration of the NetAtmo thermostat. 
It is almost done but I am looking into merging your pull request as well. 
Since I've changed the code style and the login method of both drivers I am going through your code manually. The problem I have is that I do not have access to a weather station with modules. Could you send me the raw json response of the `/api/getstationsdata` call so I can test with that static data?

Regards,
Bas
App developer at Athom

**Comment by Dijker** [comment]
@BasKiers , can you send me an email? Geurt at dijker dot nu

**Comment by freemann** [comment]
Here you go!

```
{
	"devices": [{
		"_id": "xx:ee:xx:02:xx:0c",
		"cipher_id": "enc:16:N56PDTxxxxxx+jJGb3L",
		"last_status_store": 1464297396,
		"modules": [{
			"_id": "xx:00:xx:02:xx:9c",
			"type": "NAModule1",
			"last_message": 1464297393,
			"last_seen": 1464297386,
			"dashboard_data": {
				"time_utc": 1464297335,
				"Temperature": 13.3,
				"temp_trend": "down",
				"Humidity": 84,
				"date_max_temp": 1464274061,
				"date_min_temp": 1464234435,
				"min_temp": 7.8,
				"max_temp": 20.7
			},
			"data_type": ["Temperature", "Humidity"],
			"module_name": "Tuin",
			"last_setup": 1396886557,
			"battery_vp": 4906,
			"battery_percent": 54,
			"rf_status": 72,
			"firmware": 44
		}, {
			"_id": "xx:00:xx:00:xx:f4",
			"type": "NAModule3",
			"last_message": 1464297393,
			"last_seen": 1464297386,
			"dashboard_data": {
				"time_utc": 1464297373,
				"Rain": 0,
				"sum_rain_24": 0,
				"sum_rain_1": 0
			},
			"data_type": ["Rain"],
			"module_name": "Regenmeter",
			"last_setup": 1399925225,
			"battery_vp": 5114,
			"battery_percent": 63,
			"rf_status": 83,
			"firmware": 8
		}, {
			"_id": "xx:00:xx:00:xx:d8",
			"type": "NAModule4",
			"last_message": 1464297393,
			"last_seen": 1464297354,
			"dashboard_data": {
				"time_utc": 1464297354,
				"Temperature": 21.4,
				"temp_trend": "stable",
				"Humidity": 55,
				"CO2": 864,
				"date_max_temp": 1464281616,
				"date_min_temp": 1464241067,
				"min_temp": 20.3,
				"max_temp": 21.8
			},
			"data_type": ["Temperature", "CO2", "Humidity"],
			"module_name": "Slaapkamer",
			"last_setup": 1399910040,
			"battery_vp": 5154,
			"battery_percent": 53,
			"rf_status": 67,
			"firmware": 44
		}, {
			"_id": "xx:00:xx:01:xx:02",
			"type": "NAModule4",
			"last_message": 1464297393,
			"last_seen": 1464297354,
			"dashboard_data": {
				"time_utc": 1464297354,
				"Temperature": 19.9,
				"temp_trend": "stable",
				"Humidity": 66,
				"CO2": 704,
				"date_max_temp": 1464285512,
				"date_min_temp": 1464236249,
				"min_temp": 18.7,
				"max_temp": 20.1
			},
			"data_type": ["Temperature", "CO2", "Humidity"],
			"module_name": "Badkamer ",
			"last_setup": 1423306315,
			"battery_vp": 5700,
			"battery_percent": 83,
			"rf_status": 85,
			"firmware": 44
		}, {
			"_id": "xx:00:xx:00:xx:90",
			"type": "NAModule2",
			"last_message": 1464297393,
			"last_seen": 1464297393,
			"dashboard_data": {
				"WindAngle": 29,
				"WindStrength": 1,
				"GustAngle": 45,
				"GustStrength": 3,
				"time_utc": 1464297374,
				"WindHistoric": [{
					"WindStrength": 0,
					"WindAngle": -1,
					"time_utc": 1464294060
				}, {
					"WindStrength": 0,
					"WindAngle": -1,
					"time_utc": 1464294361
				}, {
					"WindStrength": 0,
					"WindAngle": -1,
					"time_utc": 1464294662
				}, {
					"WindStrength": 0,
					"WindAngle": -1,
					"time_utc": 1464294963
				}, {
					"WindStrength": 0,
					"WindAngle": -1,
					"time_utc": 1464295264
				}, {
					"WindStrength": 0,
					"WindAngle": -1,
					"time_utc": 1464295565
				}, {
					"WindStrength": 0,
					"WindAngle": -1,
					"time_utc": 1464295861
				}, {
					"WindStrength": 0,
					"WindAngle": -1,
					"time_utc": 1464296169
				}, {
					"WindStrength": 0,
					"WindAngle": -1,
					"time_utc": 1464296469
				}, {
					"WindStrength": 1,
					"WindAngle": 45,
					"time_utc": 1464296770
				}, {
					"WindStrength": 1,
					"WindAngle": 8,
					"time_utc": 1464297072
				}, {
					"WindStrength": 1,
					"WindAngle": 29,
					"time_utc": 1464297374
				}],
				"date_max_wind_str": 1464279199,
				"date_max_temp": 1464213783,
				"date_min_temp": 1464213783,
				"min_temp": 0,
				"max_temp": 0,
				"max_wind_angle": 354,
				"max_wind_str": 13
			},
			"data_type": ["Wind"],
			"module_name": "Windmeter",
			"last_setup": 1451057130,
			"battery_vp": 5565,
			"battery_percent": 79,
			"rf_status": 88,
			"firmware": 17
		}],
		"place": {
			"altitude": -2,
			"city": "Onbekend",
			"country": "NL",
			"timezone": "Europe/Amsterdam",
			"location": [4.00, 52.00]
		},
		"station_name": "snoekie",
		"type": "NAMain",
		"dashboard_data": {
			"AbsolutePressure": 1019.1,
			"time_utc": 1464297379,
			"Noise": 42,
			"Temperature": 21.1,
			"temp_trend": "stable",
			"Humidity": 64,
			"Pressure": 1018.8,
			"pressure_trend": "stable",
			"CO2": 1450,
			"date_max_temp": 1464280410,
			"date_min_temp": 1464236872,
			"min_temp": 19.7,
			"max_temp": 21.5
		},
		"data_type": ["Temperature", "CO2", "Humidity", "Noise", "Pressure"],
		"co2_calibrating": false,
		"date_setup": 1396886559,
		"last_setup": 1396886559,
		"module_name": "Woonkamer ",
		"firmware": 124,
		"last_upgrade": 1440070622,
		"wifi_status": 54
	}],
	"user": {
		"mail": "xxxx@xxx.nl",
		"administrative": {
			"country": "NL",
			"feel_like_algo": 0,
			"lang": "nl-NL",
			"pressureunit": 0,
			"reg_locale": "nl-NL",
			"unit": 0,
			"windunit": 0
		}
	}
}
```

**Comment by BasKiers** [comment]
fixed in #8

**Pull request closed without merging**
